---
- block:
  - name: set_fact container_exec_cmd_nfs
    set_fact:
      container_exec_cmd_nfs: "{{ container_binary }} exec ceph-mon-{{ hostvars[groups[mon_group_name][0]]['ansible_hostname'] }}"
    when: containerized_deployment | bool

  - name: check if rados index object exists
    shell: "{{ container_exec_cmd_nfs | default('') }} rados -p {{ cephfs_data_pool.name }} --cluster {{ cluster }} ls|grep {{ ceph_nfs_rados_export_index }}"
    changed_when: false
    failed_when: false
    register: rados_index_exists
    check_mode: no
    when: ceph_nfs_rados_backend | bool
    delegate_to: "{{ groups[mon_group_name][0] }}"
    run_once: true

  - name: create an empty rados index object
    command: "{{ container_exec_cmd_nfs | default('') }} rados -p {{ cephfs_data_pool.name }} --cluster {{ cluster }} put {{ ceph_nfs_rados_export_index }} /dev/null"
    when:
      - ceph_nfs_rados_backend | bool
      - rados_index_exists.rc != 0
    delegate_to: "{{ groups[mon_group_name][0] }}"
    run_once: true
  when: groups.get(mon_group_name, []) | length > 0

- name: create /etc/ganesha
  file:
    path: /etc/ganesha
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: generate ganesha configuration file
  template:
    src: "ganesha.conf.j2"
    dest: /etc/ganesha/ganesha.conf
    owner: "root"
    group: "root"
    mode: "0644"
  notify: restart ceph nfss

- name: create exports directory
  file:
    path: /etc/ganesha/export.d
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  when: ceph_nfs_dynamic_exports | bool

- name: create exports dir index file
  copy:
    content: ""
    force: no
    dest: /etc/ganesha/export.d/INDEX.conf
    owner: "root"
    group: "root"
    mode: "0644"
  when: ceph_nfs_dynamic_exports | bool

- name: include_tasks systemd.yml
  include_tasks: systemd.yml
  when: containerized_deployment | bool

- name: systemd start nfs container
  systemd:
    name: ceph-nfs@{{ ceph_nfs_service_suffix | default(ansible_hostname) }}
    state: started
    enabled: yes
    masked: no
    daemon_reload: yes
  when:
    - containerized_deployment | bool
    - ceph_nfs_enable_service | bool

### FIX radut

- name: "Template {{ cluster }}.client.{{ceph_nfs_ceph_user}}.keyring"
  copy:
    content: "[client.{{ceph_nfs_ceph_user}}]\n\tkey = {{ceph_nfs_ceph_key}}"
    dest: "/etc/ceph/{{ cluster }}.client.{{ceph_nfs_ceph_user}}.keyring"
    owner: "root"
    group: "root"
    mode: "0644"
  when:
    - nfs_file_gw | bool
    - ceph_nfs_ceph_key is defined

- name: Make /usr/lib/nfs-ganesha-config.sh executable
  file:
    path: /usr/lib/nfs-ganesha-config.sh
    state: file
    owner: "root"
    group: "root"
    mode: "0755"
  when:
    - not containerized_deployment
    - ceph_nfs_enable_service

- name: Fix /lib/systemd/system/nfs-ganesha-config.service ExecStart
  become: true
  lineinfile:
    dest: "/lib/systemd/system/nfs-ganesha-config.service"
    regexp: "ExecStart="
    line: "ExecStart=/usr/lib/nfs-ganesha-config.sh"
    state: present
  when:
    - not containerized_deployment
    - ceph_nfs_enable_service

- name: "systemctl daemon-reload"
  command: systemctl daemon-reload
  when:
    - not containerized_deployment
    - ceph_nfs_enable_service

- name: restart nfs-ganesha-config
  systemd:
    name: nfs-ganesha-config
    state: restarted
    enabled: yes
  when:
    - not containerized_deployment
    - ceph_nfs_enable_service
### END FIX radut


- name: start nfs gateway service
  systemd:
    name: nfs-ganesha
    state: started
    enabled: yes
    masked: no
  when:
    - not containerized_deployment | bool
    - ceph_nfs_enable_service | bool
